### ISSUE TITLE
HTTP cache is not working as expected

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#632]
Various reports in slack questioning the effectiveness of Workbench's HTTP caching. Here's what we know:

* Prior to work on #608, requests_cache used its default "sqlite" backend with a cache that never expires (the default `expire_after` setting doesn't appear to be documented and looking at the library's [source code](https://github.com/requests-cache/requests-cache/blob/main/requests_cache/backends/base.py) reveals a default value of `None`).
* Work coming of that issue added the ability to override in configuration the backend (with 'sqlite' and 'memory' options, 'memory' default) and cache expiry (1200 seconds default).
* Commit 5429ef8 (June 5) should have resolved caching issues for most people. Running Workbench on Ubuntu 22.04, which apparently reports out of memory errors prematurely, may benefit from using `sqlite` as their cache storage backend.

I think it would be premature to make changes to the Workbench code until we can get more consistent information on why people are experiencing issues with their caches. However, disabling caching entirely (using `enable_http_cache: false` in the configuration file) seems to avoid these issues, at the cost of slowing down Workbench.

If you are reporting what you suspect are caching issues (e.g. nodes that do exist are reported not to exist, fields that exist on content types are reported not to exist, taxonomy terms that are being created in duplicates), please report them here. It would help narrow down the problem if you include:

1. what commit your Workbench code is running at
2. the operating system of the computer running Workbench
3. if you have included any of the following settings (introduced on or just before June 5) in your config file, and if so, what their values are:
    - enable_http_cache
    - http_cache_storage
    - http_cache_storage_expire_after

**Comment by mjordan** [comment]
One possible improvement we should consider is, when using the sqlite cache backend, have Workbench delete the database file from the get go. This would eliminate the possibility of a stale cache.

**Comment by flummingbird** [comment]
Hi Mark, 

I'm on commit b2fd24cc03321dd3a5aa3f677a913c2cf134520d

I'm running workbench on Ubuntu 20.04.6 

In my WorkbenchConfig.py I have:

'enable_http_cache': False,
'http_cache_storage': 'memory',
'http_cache_storage_expire_after': 1200,

when trying to run a config that has worked in the past, these are the warnings that get printed, and nothing gets ingested:
"
Warning: Query of ID map for parent ID "hnoc-p16313coll65:collection" returned multiple node IDs: 1, 309, 1, 1, 1, 1. Skpping population of field_member_of.
Warning: Query of ID map for parent ID "hnoc-p16313coll65:14" returned multiple node IDs: 18, 19. Skpping population of field_member_of.
"

**Comment by mjordan** [comment]
Hi everyone, I've pushed up some changes that will help with the caching irregularities, and that will vastly reduce the warnings that @flummingbird encountered. On the caching issue, Workbench now deletes the SQLite database file (where the cache is stored) when it starts running, so each run of Workbench starts with a fresh cache (the equivalent to when the `memory` cache backend is configured).

**Comment by flummingbird** [comment]
This resolved the issue is resolved for me. Thanks Mark!

**Comment by noahwsmith** [comment]
At Born-Digital we're still a little skeptical that the cache entries are expiring during runs - but we haven't been able to prove this. We had a `sqlite` db grow to 77gb yesterday with an expiration of 1200.

**Comment by noahwsmith** [comment]
I wonder if we need to call 
https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.patcher.html#requests_cache.patcher.remove_expired_responses 

At the end of each row, since we're using the Patched version? Or switch to using Sessions
https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.session.html

which seem to support that `expire_after` flag on initialization. I can't find an example that does the Patch version, which we're using: `install_cache(..., expire_after=1200)`

**Comment by noahwsmith** [comment]
Yep, you're right
> [install_cache()](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.patcher.html#requests_cache.patcher.install_cache) accepts all the same parameters as [CachedSession](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.session.html#requests_cache.session.CachedSession):

thanks for flagging that...

**Comment by mjordan** [comment]
But, as you say, there is more evidence that it's not expiring than there is that it is expiring.

**Comment by JWCook** [comment]
A few pointers:
* Expiration behavior is briefly summarized in the [Readme here](https://github.com/requests-cache/requests-cache#headers-and-expiration), and documented in more detail in the [Expiration](https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html) section of the docs.
* "Expiration" in this context refers to cached response expiration (aka "staleness"), not storage backend expiration (aka TTL, pruning, etc.). Expired responses can still be reused in some situations, for example with conditional requests.
* SQLite does not have a native TTL mechanism that automatically removes expired responses, but some of the other backends do (see [Redis backend docs](https://requests-cache.readthedocs.io/en/stable/user_guide/backends/redis.html#expiration), for example)
* Options for manual cleanup are listed [here](https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html#manual-removal).

If you have any other problems or questions, feel free to open an issue or discussion on the requests-cache repo!

**Comment by noahwsmith** [comment]
Thank you! I think I understand this much better now.

Running through an example output, 35 gigs:

```bash
islandora@diglib-staging:/mnt/ingest$ ls -lah noah/http_cache.sqlite
-rw-r--r-- 1 islandora islandora_ingest 35G Jul 25 13:09 noah/http_cache.sqlite

sqlite> .tables
redirects  responses

<redirects is empty>

sqlite> .schema responses
CREATE TABLE responses (    key TEXT PRIMARY KEY,    value BLOB,     expires INTEGER);
CREATE INDEX expires_idx ON responses(expires);
```

Examples:
```bash
sqlite> SELECT * from responses order by expires ASC limit 10;
b760aae7a1d264aa|��|1687546427
68893328b7880f42|��#|1687546427
da4982bad2a07dbd|��U|1687546428
2312b3b7de5ce5f9|���|1687546428
e977f39463c8d7a6|��l|1687546428
b21328450dc213e4|���|1687546429
ffd427c7a6cabe35|��l|1687546429
d1cb02f24d4653b0|���|1687546429
8a8c2b47d6b46d6d|��T|1687546430
17fda8d67a34204e|��`|1687546430

SELECT * from responses order by expires DESC limit 10;
c56b796a89af1a17|��x|1687562388
ed6baddb664f1e48|��|1687562384
21a4dbbf0c76420f|��v|1687562378
463fc632f74c96f6|��|1687562373
54396ccfde6ed48d|��v|1687562366
880fa712b6393a03|��|1687562363
e04005a1a44e14ae|���|1687562356
6a42cc5e4b710c60|��|1687562352
7f0ea39d47b54835|���|1687562346
212fcf1322e93538|��|1687562342
```

EXPIRES timestamps, sort ASC and DESC 
> UTC time: Fri, 23 Jun 2023 23:10:40 GMT
> UTC time: Fri, 23 Jun 2023 18:54:17 GMT

That's a 5 hour timespan. The intention of the code in Workbench is to expire these at 1200 increments (seconds) = 20 minutes. So unless this was somehow run with a different value (the file is old enough that I can't prove that), then the expired items are indeed staying in the db forever.

The KEYs are unique, but unreadable  - can’t tell if there are duplicates or not
The VALUEs are blobs, unreadable to humans. But here’s one:

```
sqlite> SELECT hex(value) from responses order by expires DESC limit 1;
80049578050000000000007D94288C085F636F6E74656E74944300948C0A637265617465645F6174948C1A323032332D30362D32335432323A35393A34302E393231303133948C07656C617073656494473FE3DAEA3161A1DC8C0765787069726573948C1A323032332D30362D32335432333A31393A34372E383533383630948C0768656164657273947D94288C0444617465948C1D4672692C203233204A756E20323032332032323A35393A343720474D54948C0C436F6E74656E742D54797065948C0A696D6167652F74696666948C0E436F6E74656E742D4C656E677468948C083236363433313432948C0A436F6E6E656374696F6E948C0A6B6565702D616C697665948C195374726963742D5472616E73706F72742D5365637572697479948C356D61782D6167653D31353736383030302C206D61782D6167653D33313533363030303B20696E636C756465537562446F6D61696E73948C16582D436F6E74656E742D547970652D4F7074696F6E73948C106E6F736E6966662C206E6F736E696666948C0745787069726573948C1D53756E2C203139204E6F7620313937382030353A30303A303020474D54948C0D43616368652D436F6E74726F6C948C227075626C69632C206D7573742D726576616C69646174652C206D61782D6167653D30948C0D4C6173742D4D6F646966696564948C1D4672692C203138204F637420323031392031373A33353A313320474D54948C0F582D4672616D652D4F7074696F6E73948C0A73616D656F726967696E948C10582D5853532D50726F74656374696F6E948C0D313B206D6F64653D626C6F636B948C0F43462D43616368652D537461747573948C0744594E414D4943948C095265706F72742D546F948CFF7B22656E64706F696E7473223A5B7B2275726C223A2268747470733A5C2F5C2F612E6E656C2E636C6F7564666C6172652E636F6D5C2F7265706F72745C2F76333F733D49677934426B596345572532464B57766D486D38376F585546633735735A4C53797664515A426166794F39785A706168306544703635656C3674475A6B72344F4F385A467847664A774779733937323343253242344C7977635142616E334932325459756548374866436B6C516A74253246634E53496B743064534E487071526F444D547234703049754D3071725251253344253344227D5D2C2267726F7570223A2263662D6E656C222C226D61785F616765223A3630343830307D948C034E454C948C3C7B22737563636573735F6672616374696F6E223A302C227265706F72745F746F223A2263662D6E656C222C226D61785F616765223A3630343830307D948C06536572766572948C0A636C6F7564666C617265948C0643462D524159948C14376463303537656637646565386333362D455752948C07616C742D737663948C1368333D223A343433223B206D613D383634303094758C06726561736F6E948C024F4B948C0772657175657374947D94288C04626F647994680268087D94288C06416363657074948C032A2F2A948C0F4163636570742D456E636F64696E67948C0D6465666C6174652C20677A6970948C0A436F6E6E656374696F6E948C0A6B6565702D616C697665948C0A557365722D4167656E74948C16707974686F6E2D72657175657374732F322E32352E3194758C066D6574686F64948C0448454144948C0375726C948C4D68747470733A2F2F6469676C69622E616D7068696C736F632E6F72672F69736C616E646F72612F6F626A6563742F746578743A3235383838312F6461746173747265616D2F4F424A2F7669657794758C0B7374617475735F636F6465944BC8683C8C4D68747470733A2F2F6469676C69622E616D7068696C736F632E6F72672F69736C616E646F72612F6F626A6563742F746578743A3235383838312F6461746173747265616D2F4F424A2F7669657794752E
```

From JWCook’s [response in prev comment](https://github.com/mjordan/islandora_workbench/issues/632#issuecomment-1648554232),  I read that as saying “we need to call the manual expiration cleanup routine as part of one of our big loops” (maybe inside every CSV row or something). That code in our case looks like it will be:
`requests_cache.delete(expired=True)`

if that doesn’t work, we may instead need to pass the expiration time in that manual expiry call - e.g. something like 
`requests_cache.delete(older_than=timedelta(seconds=config['http_cache_storage_expire_after']))`

OR we could switch from `sqlite` to one of these back ends which might just clean up after themselves: DynamoDb, MongoDb, Redis. That seems like a distant second option because it would require additional dependency installation. I’d like to fix it with the tools we’re using, if we can.

Looking at where to call the manual expiry, i think it might be best to do this at the beginning of “for each CSV row” loop in the CREATE function: https://github.com/mjordan/islandora_workbench/blob/122895da3d99a3ad7ee9037d30e8028fb69e0ac2/workbench#L78

We could put it AFTER each row is processed, but there are a lot of conditionals being processed in that function and I think we want to guarantee that this will happen with each row. The top of that function is just a lot cleaner than the remainder of it, and having this up front will be a lot more legible for the future. I will test this and see where it lands us…

**Comment by noahwsmith** [comment]
`-rw-r--r--  1 islandora        islandora_ingest 595M Jul 26 14:01  http_cache.sqlite`
after 40 minutes of runtime

```bash
sqlite> SELECT * from responses order by expires ASC limit 10;
2e89a6981d65e27e|��|1690394636
40ed67cb3d6afcd5|��v|1690394639
9deebd737de52d70|��|1690394672
ffbb07330c5ba7d4|��}|1690394674
970c88eddc614ec7|��|1690394722
c532b06b9621b7e2|��x|1690394725
3274064b883157e3|��|1690394760
98c0dca5c8c2c490|��t|1690394763
83def373bafa3a68|��|1690394801
2cb948153ff80680|��r|1690394804
sqlite> SELECT * from responses order by expires DESC limit 10;
5c14b37c293b5146|��}|1690395836
92e42bc8c617bbfc|���|1690395802
2d21d1f7ccea3530|��|1690395799
9f7737709c84b05a|��[|1690395741
e4dafb4d33fee816|���|1690395740
3496c70ebafe5bb9|��|1690395740
9d9ca3d6ac6c2ace|���|1690395700
125c0a4be96627d2|��|1690395696
7002b5ca8f43782b|��}|1690395657
aad6d0d5f3e77c6f|��|1690395653
```

Wed Jul 26 2023 18:03:56 GMT+0000
Wed Jul 26 2023 18:23:56 GMT+0000

20 minutes exactly! I'll push a PR with this one line change... And we'll also test the memory version to see if this prevents OOM Kills on latest Ubuntu systems.

**Comment by aOelschlager** [comment]
First, I want to say thank you for adding this! I think it would also be a great enhancement to add the request_cache.delete to all of the other functions at the beginning of the csv data loop as they do not call the create function but would benefit from the deleted cache: https://github.com/search?q=repo%3Amjordan%2Fislandora_workbench++%22for+row+in+csv_data%22&type=code

**Comment by mjordan** [comment]
@aOelschlager I think you're correct. I will add @noahwsmith's fix to all of the task functions.

**Comment by mjordan** [comment]
With commit 63b3b83c94eb94dbfc9b6ef23ca8f2454682f3f8 I've added the cache pruning call to all task functions, and also wrapped the call in logic to account for `enable_http_cache: false`.

**Comment by mjordan** [comment]
I'm going to revert using .delete() in the other tasks for now. I just tried an update task and I'm getting:

```
│    407 │   for row in csv_data:                                                                  │
│    408 │   │   # Delete expired items from request_cache before processing a row.                │
│    409 │   │   if config['enable_http_cache'] is True:                                           │
│ >  410 │   │   │   requests_cache.patcher.delete(expired=True)                                   │
│    411 │   │                                                                                     │
│    412 │   │   if not value_is_numeric(row['node_id']):                                          │
│    413 │   │   │   row['node_id'] = get_nid_from_url_alias(config, row['node_id'])               │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: module 'requests_cache.patcher' has no attribute 'delete'
```

Will look at this later.

**Comment by mjordan** [comment]
Can't replicate the error I hit in previous comment.

**Comment by dara2** [comment]
I found a possible bug (or maybe it needs documentation?) in the `get_data_from_view` task. When I ran it with the configs as documented at https://mjordan.github.io/islandora_workbench_docs/generating_csv_files/#using-a-drupal-view-to-identify-content-to-export-as-csv, I got this error:
```
islandora@islandora01:/opt/islandora_workbench$ ./workbench --config JFABC_Publisher_Update.yml
OK, connection to Drupal at https://digitalcollections.saic.edu/ verified.
"Get data from View" task started using config file JFABC_Publisher_Update.yml.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /opt/islandora_workbench/./workbench:2166 in <module>                        │
│                                                                              │
│   2163 │   if config['task'] == 'export_csv':                                │
│   2164 │   │   export_csv()                                                  │
│   2165 │   if config['task'] == 'get_data_from_view':                        │
│ ❱ 2166 │   │   get_data_from_view()                                          │
│   2167 │   if config['task'] == 'create_terms':                              │
│   2168 │   │   create_terms()                                                │
│   2169 │   if config['task'] == 'update_media':                              │
│ /opt/islandora_workbench/./workbench:1672 in get_data_from_view              │
│                                                                              │
│   1669 │   for node in nodes:                                                │
│   1670 │   │   # Delete expired items from request_cache before processing a │
│   1671 │   │   if config['enable_http_cache'] is True:                       │
│ ❱ 1672 │   │   │   requests_cache.delete(expired=True)                       │
│   1673 │   │                                                                 │
│   1674 │   │   if node['nid'][0]['value'] not in seen_nids:                  │
│   1675 │   │   │   if node['type'][0]['target_id'] == config['content_type'] │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'requests_cache' has no attribute 'delete'
```
So I added in a line `enable_http_cache: false` and now it’s working.

**Comment by mjordan** [comment]
It's not documentation, deleting lines from the cache should work silently, with no user intervention. Given sporadic occurrence of this error, I am guessing that if the cache is empty, it can't "delete". I am going to try to confirm that.

**Comment by mjordan** [comment]
@JWCook I've seen the `AttributeError: module 'requests_cache' has no attribute 'delete'` error reported above myself but it's definitely not happening consistently. Note that this is different than the exception reported at https://github.com/requests-cache/requests-cache/issues/111. Any tips on tracking down what's causing this or how we can program defensively to avoid it?

I can open an issue on https://github.com/requests-cache/requests-cache/issues/ if you prefer.

**Comment by mjordan** [comment]
Thanks - on the machine I noticed it on, `pip freeze` produces `requests-cache==1.0.0a1`. On the machine I can't reproduce it on, I get `requests-cache==1.0.0b0`.

@dara2 what version of requests-cache does running `pip freeze` show for you?

**Comment by JWCook** [comment]
`1.0.0a1` would have been an earlier alpha release used for testing; I'd recommend using a stable release.

**Comment by mjordan** [comment]
OK, thanks, I've just updated requests-cache to 1.1.0 on the machine I noticed on and will smoke test to see if the error persists.

**Comment by mjordan** [comment]
@JWCook success. On the machine that threw the exception, after updating requests-cache to 1.1.0, Islandora Workbench ran as expected. Thanks! I'll advise our users to update ASAP. Your library has really made a big difference in the performance of our tool. Thanks again.

**Comment by JWCook** [comment]
Glad to hear it! Feel free to reach out if you run into any more problems.
